#pragma once

#include <QHash>
#include <QString>

// 公式Managerの文字列テーブル (strtable_ja.stb) の CT_* から生成した、GetCaps の項目名→表示名の対応表。
namespace CapsLabels {

inline const QHash<QString, QString> &table()
{
    static const QHash<QString, QString> kTable = {
        {QStringLiteral("i_max_packet_size"), QString::fromUtf8("最大 Ethernet パケットサイズ")},
        {QStringLiteral("i_max_hubs"), QString::fromUtf8("最大仮想 HUB 数")},
        {QStringLiteral("i_max_user_creation"), QString::fromUtf8("最大作成可能ユーザー数")},
        {QStringLiteral("i_max_sessions"), QString::fromUtf8("最大同時接続可能セッション数")},
        {QStringLiteral("i_max_clients"), QString::fromUtf8("最大クライアントセッション数")},
        {QStringLiteral("i_max_bridges"), QString::fromUtf8("最大ブリッジセッション数")},
        {QStringLiteral("i_max_users_per_hub"), QString::fromUtf8("登録可能な最大ユーザー数 / 仮想 HUB")},
        {QStringLiteral("i_max_groups_per_hub"), QString::fromUtf8("登録可能な最大グループ数 / 仮想 HUB")},
        {QStringLiteral("i_max_access_lists"), QString::fromUtf8("登録可能な最大アクセスリスト数 / 仮想 HUB")},
        {QStringLiteral("i_max_mac_tables"), QString::fromUtf8("MAC アドレステーブル最大サイズ / 仮想 HUB")},
        {QStringLiteral("i_max_ip_tables"), QString::fromUtf8("IP アドレステーブル最大サイズ / 仮想 HUB")},
        {QStringLiteral("i_max_secnat_tables"), QString::fromUtf8("SecureNAT テーブル最大サイズ / 仮想 HUB")},
        {QStringLiteral("i_max_l3_sw"), QString::fromUtf8("登録可能な最大仮想レイヤ 3 スイッチ数")},
        {QStringLiteral("i_max_l3_if"), QString::fromUtf8("登録可能な最大仮想インターフェイス数 / レイヤ 3 スイッチ")},
        {QStringLiteral("i_max_l3_table"), QString::fromUtf8("登録可能な最大ルーティングテーブル数 / レイヤ 3 スイッチ")},
        {QStringLiteral("b_bridge"), QString::fromUtf8("VPN Bridge ソフトウェアとして動作")},
        {QStringLiteral("b_standalone"), QString::fromUtf8("スタンドアロンモード")},
        {QStringLiteral("b_cluster_controller"), QString::fromUtf8("クラスタコントローラモード")},
        {QStringLiteral("b_cluster_member"), QString::fromUtf8("クラスタメンバモード")},
        {QStringLiteral("b_vpn_client_connect"), QString::fromUtf8("VPN Client / Bridge から接続が可能")},
        {QStringLiteral("b_local_bridge"), QString::fromUtf8("ローカルブリッジ機能が使用可能")},
        {QStringLiteral("b_must_install_pcap"), QString::fromUtf8("パケットキャプチャドライバが未インストール")},
        {QStringLiteral("b_tap_supported"), QString::fromUtf8("tun/tap が使用可能 (Linux のみ)")},
        {QStringLiteral("b_support_config_hub"), QString::fromUtf8("仮想 HUB の設定の変更が可能")},
        {QStringLiteral("b_support_securenat"), QString::fromUtf8("SecureNAT 機能が使用可能")},
        {QStringLiteral("b_virtual_nat_disabled"), QString::fromUtf8("仮想 NAT 機能は無効 (仮想 DHCP 機能のみ有効)")},
        {QStringLiteral("b_support_cascade"), QString::fromUtf8("カスケード接続が使用可能")},
        {QStringLiteral("b_support_cascade_cert"), QString::fromUtf8("カスケード接続時にサーバー認証が使用可能")},
        {QStringLiteral("b_support_config_log"), QString::fromUtf8("ログ保存設定の変更が可能")},
        {QStringLiteral("b_support_autodelete"), QString::fromUtf8("ログファイルの自動削除が使用可能")},
        {QStringLiteral("b_support_radius"), QString::fromUtf8("外部認証サーバーによる認証設定が可能")},
        {QStringLiteral("b_support_config_rw"), QString::fromUtf8("リモートで Config ファイルの読み書きが可能")},
        {QStringLiteral("b_support_hub_admin_option"), QString::fromUtf8("仮想 HUB の管理オプションが設定可能")},
        {QStringLiteral("b_support_cascade_client_cert"), QString::fromUtf8("カスケード接続時にクライアント証明書が使用可能")},
        {QStringLiteral("b_support_hide_hub"), QString::fromUtf8("匿名ユーザーへの仮想 HUB の列挙を禁止することが可能")},
        {QStringLiteral("b_support_cluster_admin"), QString::fromUtf8("複数サーバーに分散したクラスタの統合管理が可能")},
        {QStringLiteral("b_support_cluster"), QString::fromUtf8("クラスタの一部として動作可能")},
        {QStringLiteral("b_support_cluster_controller"), QString::fromUtf8("クラスタコントローラとして動作中")},
        {QStringLiteral("b_support_layer3"), QString::fromUtf8("仮想レイヤ 3 スイッチ機能をサポート")},
        {QStringLiteral("b_support_crl"), QString::fromUtf8("無効な証明書の一覧を仮想 HUB ごとに設定可能")},
        {QStringLiteral("b_support_ac"), QString::fromUtf8("接続元 IP 制限リストを仮想 HUB ごとに設定可能")},
        {QStringLiteral("b_support_read_log"), QString::fromUtf8("ログファイルのダウンロードが可能")},
        {QStringLiteral("b_support_rename_cascade"), QString::fromUtf8("カスケード接続設定の名前の変更が可能")},
        {QStringLiteral("b_support_license"), QString::fromUtf8("ライセンス管理が可能")},
        {QStringLiteral("b_support_limit_multilogin"), QString::fromUtf8("同一ユーザーの多重ログイン数の制限を設定可能")},
        {QStringLiteral("b_support_qos"), QString::fromUtf8("VoIP / QoS 対応機能が利用可能")},
        {QStringLiteral("b_support_syslog"), QString::fromUtf8("syslog 機能が利用可能")},
        {QStringLiteral("b_cluster_hub_type_fixed"), QString::fromUtf8("クラスタ内の仮想 HUB の種類が固定されている")},
        {QStringLiteral("b_beta_version"), QString::fromUtf8("ベータ版 (プレリリースビルド) である")},
        {QStringLiteral("b_support_check_mac"), QString::fromUtf8("アクセスリストで MAC アドレスを指定可能")},
        {QStringLiteral("b_support_check_tcp_state"), QString::fromUtf8("TCP コネクションの状態でパケットフィルタリングが可能")},
        {QStringLiteral("b_support_network_connection_name"), QString::fromUtf8("物理的な LAN カードの別名を取得することが可能")},
        {QStringLiteral("b_support_radius_retry_interval_and_several_servers"), QString::fromUtf8("RADIUS 認証で再試行間隔および複数サーバー指定が可能")},
        {QStringLiteral("b_support_vlan"), QString::fromUtf8("MAC アドレステーブルでタグ VLAN の ID を管理可能")},
        {QStringLiteral("b_support_hub_ext_options"), QString::fromUtf8("仮想 HUB 拡張オプションをサポート")},
        {QStringLiteral("b_support_policy_ver_3"), QString::fromUtf8("セキュリティポリシー バージョン 3.0 をサポート")},
        {QStringLiteral("b_support_ipv6_acl"), QString::fromUtf8("IPv6 アクセスリストをサポート")},
        {QStringLiteral("b_support_ex_acl"), QString::fromUtf8("アクセスリストで遅延・ジッタ・パケットロスの設定をサポート")},
        {QStringLiteral("b_support_acl_group"), QString::fromUtf8("アクセスリストでグループ名による条件の指定をサポート")},
        {QStringLiteral("b_support_ipv6_ac"), QString::fromUtf8("IPv6 接続元 IP 制限リストをサポート")},
        {QStringLiteral("b_support_eth_vlan"), QString::fromUtf8("タグ VLAN パケット透過設定ツールをサポート")},
        {QStringLiteral("b_support_msg"), QString::fromUtf8("仮想 HUB への VPN 接続時のメッセージ表示機能をサポート")},
        {QStringLiteral("b_vpn3"), QString::fromUtf8("内部バージョン 3.0 の新機能")},
        {QStringLiteral("b_vpn4"), QString::fromUtf8("内部バージョン 4.0 の新機能")},
        {QStringLiteral("b_support_ipsec"), QString::fromUtf8("IPsec / L2TP / EtherIP / L2TPv3 サーバー機能")},
        {QStringLiteral("b_support_sstp"), QString::fromUtf8("MS-SSTP VPN サーバー機能")},
        {QStringLiteral("b_support_udp_acceleration"), QString::fromUtf8("UDP アクセラレーション機能")},
        {QStringLiteral("b_support_openvpn"), QString::fromUtf8("OpenVPN サーバー機能")},
        {QStringLiteral("b_support_ddns"), QString::fromUtf8("ダイナミック DNS クライアント機能")},
        {QStringLiteral("b_support_ddns_proxy"), QString::fromUtf8("DDNS クライアントのプロキシサーバー経由の接続")},
        {QStringLiteral("b_support_special_listener"), QString::fromUtf8("VPN over ICMP および VPN over DNS 接続の受付け")},
        {QStringLiteral("b_support_redirect_url_acl"), QString::fromUtf8("アクセスリストで HTTP の URL リダイレクト機能をサポート")},
        {QStringLiteral("b_is_in_vm"), QString::fromUtf8("VM (仮想マシン) 内で動作中")},
        {QStringLiteral("b_support_azure"), QString::fromUtf8("VPN Azure 機能が利用可能")},
        {QStringLiteral("b_support_aes_ni"), QString::fromUtf8("CPU AES Acceleration (AES-NI) が動作中")},
        {QStringLiteral("b_using_selow_driver"), QString::fromUtf8("SoftEther 軽量カーネルモード Ethernet ドライバを使用中")},
        {QStringLiteral("b_support_vgs"), QString::fromUtf8("VPN Gate サービス サーバー機能が利用可能")},
        {QStringLiteral("b_support_vgs_in_client"), QString::fromUtf8("VPN Gate サービス サーバー機能 (VPN Client 統合)")},
        {QStringLiteral("b_is_softether"), QString::fromUtf8("無償版またはオープンソース版の SoftEther VPN である")},
        {QStringLiteral("b_suppport_push_route"), QString::fromUtf8("静的ルーティングテーブルのプッシュ機能")},
        {QStringLiteral("b_suppport_push_route_config"), QString::fromUtf8("静的ルーティングテーブルのプッシュ機能 (設定可)")},
    };
    return kTable;
}

} // namespace CapsLabels
