#pragma once

// 自動生成: docs/upstream-reference/strtable_ja.stb の HUB_AO_* から。
// 仮想HUB管理オプション / 拡張オプションの項目名 → 日本語の説明文。

#include <QCoreApplication>
#include <QHash>
#include <QString>

namespace HubOptionTexts {

inline QString description(const QString &name)
{
    static const QHash<QString, const char *> table = {
        {QStringLiteral("CLICK"), "項目名を 1 つ選択すると、その項目名に関する説明文が表示されます。"},
        {QStringLiteral("UNKNOWN"), "この項目に関する説明文が見つかりませんでした。ドキュメント等を参照するか、項目名をもとに意味・内容を推測して利用してください。"},
        {QStringLiteral("allow_hub_admin_change_option"), "この項目は特殊です。この項目が 1 (有効) の場合は、VPN Server 全体の管理者だけでなく仮想 HUB の管理者も自ら仮想 HUB 管理オプションを変更することができるようになります。"},
        {QStringLiteral("deny_hub_admin_change_ext_option"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB の拡張オプションの設定を変更することができなくなり、VPN Server 全体の管理者のみが仮想 HUB の拡張オプションの設定を変更することができるようになります。"},
        {QStringLiteral("no_delay_jitter_packet_loss"), "この項目が 1 以上に設定されている場合は、仮想 HUB のアクセスリストを追加する際に遅延・ジッタ・パケットロスを生成させるためのパラメータが設定されている場合であっても、それらの値をすべて削除します。これにより、遅延・パケットロス生成機能が実質的に無効になります。遅延・パケットロス生成機能は VPN Server の CPU およびメモリ使用率を高くする可能性があるため、多くのユーザーで共有する仮想 HUB の場合は、高負荷を避けるためにこのオプションを使用してください。"},
        {QStringLiteral("max_users"), "この項目が 1 以上に設定されている場合は、仮想 HUB に登録できるユーザーの最大数がこの項目の指定数に制限され、それ以上のユーザーオブジェクトを登録することはできなくなります。"},
        {QStringLiteral("max_multilogins_per_user"), "この項目が 1 以上に設定されている場合は、仮想 HUB に登録されている 1 個のユーザーオブジェクトに対して同時にログインし接続可能な VPN セッション数がこの項目の指定数に制限され、それ以上の VPN セッションが同一のユーザーオブジェクトを用いて VPN サーバーに接続することができなくなります。"},
        {QStringLiteral("max_groups"), "この項目が 1 以上に設定されている場合は、仮想 HUB に登録できるグループの最大数がこの項目の指定数に制限され、それ以上のグループオブジェクトを登録することはできなくなります。"},
        {QStringLiteral("max_accesslists"), "この項目が 1 以上に設定されている場合は、仮想 HUB に登録できるアクセスリスト項目の最大数がこの項目の指定数に制限され、それ以上のアクセスリスト項目を登録することはできなくなります。"},
        {QStringLiteral("max_sessions_client_bridge_apply"), "この項目が 1 以上に設定されている場合のみ、max_sessions_client および max_sessions_bridge の値が適用されます。"},
        {QStringLiteral("max_sessions"), "この項目が 1 以上に設定されている場合は、仮想 HUB に接続できる VPN セッション数がこの項目の指定数に制限され、それ以上の VPN 接続を同時に処理することはできなくなります。"},
        {QStringLiteral("max_sessions_client"), "この項目が 1 以上に設定されている場合は、仮想 HUB に接続できる VPN クライアントセッション数がこの項目の指定数に制限され、それ以上の VPN 接続を同時に処理することはできなくなります。この項目は、max_sessions_client_bridge_apply が 1 以上に設定されている場合のみ有効です。"},
        {QStringLiteral("max_sessions_bridge"), "この項目が 1 以上に設定されている場合は、仮想 HUB に接続できる VPN ブリッジセッション数がこの項目の指定数に制限され、それ以上の VPN 接続を同時に処理することはできなくなります。この項目は、max_sessions_client_bridge_apply が 1 以上に設定されている場合のみ有効です。"},
        {QStringLiteral("max_bitrates_download"), "この項目が 1 以上に設定されている場合は、仮想 HUB に接続するすべての VPN セッションのセキュリティポリシーのうち [ダウンロード帯域幅] ポリシーの値がこの項目の指定数に強制的に変更され、セッションのダウンロード速度が制限されます。たとえば、この値が 1000000 になっている場合は、この仮想 HUB に対するいかなる VPN 接続セッションでもそのダウンロード通信速度は 1 Mbps を超えることはできなくなります。"},
        {QStringLiteral("max_bitrates_upload"), "この項目が 1 以上に設定されている場合は、仮想 HUB に接続するすべての VPN セッションのセキュリティポリシーのうち [アップロード帯域幅] ポリシーの値がこの項目の指定数に強制的に変更され、セッションのアップロード速度が制限されます。たとえば、この値が 1000000 になっている場合は、この仮想 HUB に対するいかなる VPN 接続セッションでもそのアップロード通信速度は 1 Mbps を超えることはできなくなります。"},
        {QStringLiteral("deny_empty_password"), "この項目が 1 (有効) の場合は、仮想 HUB に登録されているユーザーに空のパスワードを設定することはできなくなります。もし空のパスワードが設定されているユーザーがいる場合は、そのユーザーは VPN 接続を行うことはできません (例外として、localhost からの接続は可能です)。"},
        {QStringLiteral("deny_bridge"), "この項目が 1 (有効) の場合は、仮想 HUB に対して接続されるセッションは、接続時のユーザーのセキュリティポリシーの内容にかかわらず常にブリッジが禁止されます。したがって、この仮想 HUB にブリッジ目的で接続することができなくなります。"},
        {QStringLiteral("deny_routing"), "この項目が 1 (有効) の場合は、仮想 HUB に対して接続されるセッションは、接続時のユーザーのセキュリティポリシーの内容にかかわらず常にルータ動作が禁止されます。したがって、この仮想 HUB にルーティング目的で接続することができなくなります。"},
        {QStringLiteral("deny_qos"), "この項目が 1 (有効) の場合は、仮想 HUB に対して接続されるセッションは、接続時のユーザーのセキュリティポリシーの内容にかかわらず常に QoS 機能が禁止されます。"},
        {QStringLiteral("deny_change_user_password"), "この項目が 1 (有効) の場合は、仮想 HUB のユーザーが「パスワード認証｣モードの場合、自分でパスワードを変更することができなくなります。"},
        {QStringLiteral("no_change_users"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB に新しいユーザーを追加したり、既存のユーザーを削除または編集したりすることができなくなります。"},
        {QStringLiteral("no_change_groups"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB に新しいグループを追加したり、既存のグループを削除または編集したりすることができなくなります。"},
        {QStringLiteral("no_securenat"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は SecureNAT 機能を有効または無効にすることができなくなります。"},
        {QStringLiteral("no_securenat_enablenat"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は SecureNAT 機能における仮想 NAT 機能を有効または無効にすることができなくなります。"},
        {QStringLiteral("no_securenat_enabledhcp"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は SecureNAT 機能における仮想 DHCP サーバー機能を有効または無効にすることができなくなります。"},
        {QStringLiteral("no_cascade"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者はカスケード接続を作成・削除・編集またはオンライン化 / オフライン化することができなくなります。"},
        {QStringLiteral("no_online"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者はオフライン状態の仮想 HUB をオンライン化することができなくなります。"},
        {QStringLiteral("no_offline"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者はオンライン状態の仮想 HUB をオフライン化することができなくなります。"},
        {QStringLiteral("no_change_log_config"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB のログファイルの保存設定を変更することができなくなります。"},
        {QStringLiteral("no_disconnect_session"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB に接続されている VPN セッションを指定して強制切断することができなくなります。"},
        {QStringLiteral("no_delete_iptable"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB の IP アドレステーブルデータベースから IP アドレスエントリを指定して削除することができなくなります。"},
        {QStringLiteral("no_delete_mactable"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB の MAC アドレステーブルデータベースから MAC アドレスエントリを指定して削除することができなくなります。"},
        {QStringLiteral("no_enum_session"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB に現在接続している VPN セッションの一覧を列挙できなくなります。"},
        {QStringLiteral("no_query_session"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB に現在接続している VPN セッションを指定して、そのセッションに関する詳細情報を取得することができなくなります。"},
        {QStringLiteral("no_change_admin_password"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB の管理者パスワードを変更できなくなります。"},
        {QStringLiteral("no_change_log_switch_type"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB のログファイルの保存設定のうち、[ログファイルの切り替え周期] 設定項目を変更できなくなります。"},
        {QStringLiteral("no_change_access_list"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB のアクセスリストを操作することができなくなります。"},
        {QStringLiteral("no_change_access_control_list"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB のアクセス元 IP 制限リストを操作することができなくなります。"},
        {QStringLiteral("no_change_cert_list"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB の「信頼する証明機関の証明書一覧」リストを操作することができなくなります。"},
        {QStringLiteral("no_change_crl_list"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB の「無効な証明書」リストを操作することができなくなります。"},
        {QStringLiteral("no_read_log_file"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB のログファイルを管理接続を通じて列挙したり、リモートから読み出したりすることができなくなります。"},
        {QStringLiteral("no_change_msg"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB に VPN Client が接続する際に VPN Client に表示されるべきメッセージを設定することができなくなります。"},
        {QStringLiteral("no_access_list_include_file"), "この項目が 1 (有効) の場合は、仮想 HUB の管理者は仮想 HUB にアクセスリストを追加する際に送信元または宛先ユーザー名として \"include:\" または \"exclude:\" 指定でユーザー名リストファイルを指定することができなくなります。"},
        {QStringLiteral("NoAddressPollingIPv4"), "この項目が 1 (有効) の場合は、通常、仮想 HUB が 5 秒ごとに実施するセグメント内の MAC アドレステーブルおよび IPv4 アドレステーブルのメンテナンス (IPv4 デバイスの生存確認のための ARP パケットの送信) を実施しないようになります。一定時間無通信の IPv4 デバイスは、仮想 HUB のセグメントに存在していても、一定時間 (1 分～ 10 分間) でテーブルから消去されるようになります。これによりブロードキャストパケット数を削減することができますが、いくつかの IPv4 関係のセキュリティポリシーが実質的に機能しなくなることがあります。"},
        {QStringLiteral("NoAddressPollingIPv6"), "この項目が 1 (有効) の場合は、通常、仮想 HUB が 5 秒ごとに実施するセグメント内の MAC アドレステーブルおよび IPv6 アドレステーブルのメンテナンス (IPv6 デバイスの生存確認のための ICMPv6 パケットの送信) を実施しないようになります。一定時間無通信の IPv6 デバイスは、仮想 HUB のセグメントに存在していても、一定時間 (1 分～ 10 分間) でテーブルから消去されるようになります。これによりブロードキャストパケット数を削減することができますが、いくつかの IPv6 関係のセキュリティポリシーが実質的に機能しなくなることがあります。"},
        {QStringLiteral("NoIpTable"), "この項目が 1 (有効) の場合は、仮想 HUB は IP アドレステーブルを内部的に自動構築しないようになります。これにより VPN Server の CPU およびメモリの使用量を削減することができますが、いくつかの IP 関係のセキュリティポリシーが実質的に機能しなくなることがあります。"},
        {QStringLiteral("NoMacAddressLog"), "この項目が 1 (有効) の場合は、仮想 HUB は、仮想 HUB の MAC アドレステーブルに新しい MAC アドレスが登録された場合のログをセキュリティログに書きこまないようになります。"},
        {QStringLiteral("ManageOnlyPrivateIP"), "この項目が 1 (有効) の場合は、仮想 HUB が内部的に構築する IPv4 アドレステーブルにはプライベート IPv4 アドレスのみが格納されるようになります。ここでのプライベート IPv4 アドレスとは、10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 169.254.0.0/16 を意味します。それ以外の IPv4 アドレスは IPv4 アドレステーブルに格納されないようになります。"},
        {QStringLiteral("ManageOnlyLocalUnicastIPv6"), "この項目が 1 (有効) の場合は、仮想 HUB が内部的に構築する IPv6 アドレステーブルにはローカルユニキャスト IPv6 アドレスのみが格納されるようになります。ここでのローカルユニキャスト IPv6 アドレスとは、fe80::/10 を意味します。それ以外の IPv6 アドレスは IPv6 アドレステーブルに格納されないようになります。"},
        {QStringLiteral("DisableIPParsing"), "この項目が 1 (有効) の場合は、仮想 HUB は内部的にすべての Ethernet パケットの IP ヘッダを解釈しないようになります。これにより VPN Server の CPU およびメモリの使用量を削減することができますが、仮想 HUB は IP アドレステーブルを内部的に自動構築しないようになり、いくつかの IP 関係のセキュリティポリシーが実質的に機能しなくなることがあります。"},
        {QStringLiteral("YieldAfterStorePacket"), "この項目が 1 (有効) の場合は、仮想 HUB はある VPN セッションからパケットを受け取った後、そのパケットを他の VPN セッションにストア・フォワードした直後に一旦 CPU を待機状態に設定します。これによりパケットの遅延が若干短くなる可能性がありますが、スレッドコンテキストスイッチ回数が増加することによりパフォーマンスが低下する可能性もあります。"},
        {QStringLiteral("FilterPPPoE"), "この項目が 1 (有効) の場合は、仮想 HUB はすべての PPPoE (PPP over Ethernet) パケットを破棄し、転送しないようにします。複数の LAN 同士をブリッジ接続する場合で、両方の PPPoE セグメントを分割したい場合に便利です。"},
        {QStringLiteral("FilterOSPF"), "この項目が 1 (有効) の場合は、仮想 HUB はすべての OSPF (Open Shortest Path First) パケットを破棄し、転送しないようにします。"},
        {QStringLiteral("FilterIPv4"), "この項目が 1 (有効) の場合は、仮想 HUB はすべての IPv4 パケットおよび ARP パケットを破棄し、転送しないようにします。"},
        {QStringLiteral("FilterIPv6"), "この項目が 1 (有効) の場合は、仮想 HUB はすべての IPv6 パケットを破棄し、転送しないようにします。"},
        {QStringLiteral("FilterNonIP"), "この項目が 1 (有効) の場合は、仮想 HUB はすべての非 IP パケット (IPv4, ARP, IPv6 以外の種類のパケット) を破棄し、転送しないようにします。なお、仮想 HUB を通過するすべてのタグ VLAN パケットは非 IP パケットとしてみなされます。"},
        {QStringLiteral("FilterBPDU"), "この項目が 1 (有効) の場合は、仮想 HUB はすべての BPDU (Bridge Protocol Data Unit) パケットを破棄し、転送しないようにします。これにより、すべてのスパニング・ツリーパケットが伝送されなくなります。"},
        {QStringLiteral("NoIPv6DefaultRouterInRAWhenIPv6"), "この項目が 1 (有効) の場合は、仮想 HUB に対して接続されるすべての VPN セッションは [IPv6 ルータ広告からデフォルトルータ指定を削除 (IPv6 物理接続時自動有効化)] ポリシーが自動的に有効になります。VPN Client または VPN Bridge から VPN Server に対する接続および通信に利用する物理的なプロトコルが IPv6 の場合には、その VPN セッションに対して、仮想 HUB の他のセッションの IPv6 ルータが発信する IPv6 ルータ広告メッセージのルータ有効期間の値が 0 以外の数値の場合、この値を強制的に 0 に書き換えて伝送します。これにより、VPN クライアントコンピュータが VPN 接続した先のネットワークに存在するルータをデフォルトルータとして利用することにより物理的な IPv6 通信が途切れてしまう誤作動を防止することができます。"},
        {QStringLiteral("NoLookBPDUBridgeId"), "この項目が 1 (有効) の場合は、仮想 HUB は BPDU (Bridge Protocol Data Unit) パケットの内容をもとに MAC アドレステーブルを構築する際に BPDU パケット内のフィールドに記載されている送信元 MAC アドレスを無視し、Ethernet ヘッダに記載されている送信元 MAC アドレスをもとに MAC アドレステーブルを構築します。この値はネットワークに非常に詳しい方以外は変更しないでください。"},
        {QStringLiteral("NoManageVlanId"), "この項目が 1 (有効) の場合は、仮想 HUB は MAC アドレステーブルの構築および検索において VLAN ID を管理しないようにし、すべての Ethernet パケットの VLAN タグを無視します。"},
        {QStringLiteral("VlanTypeId"), "VLAN タグの Ethernet Type ID (TPID) の値を 10 進数で指定します。この値はデフォルトでは 33024 (16 進数で 0x8100) です。この値はネットワークに非常に詳しい方以外は変更しないでください。"},
        {QStringLiteral("FixForDLinkBPDU"), "この項目が 1 (有効) の場合は、FixForDLinkBPDU オプションが有効になります。この値はネットワークに非常に詳しい方以外は変更しないでください。"},
        {QStringLiteral("NoIPv4PacketLog"), "この項目が 1 (有効) の場合は、仮想 HUB を流れるすべての IPv4 パケットに関するパケットログが保存されないようになります。"},
        {QStringLiteral("NoIPv6PacketLog"), "この項目が 1 (有効) の場合は、仮想 HUB を流れるすべての IPv6 パケットに関するパケットログが保存されないようになります。"},
        {QStringLiteral("NoSpinLockForPacketDelay"), "この項目が 1 (有効) の場合は、仮想 HUB のアクセスリストによってパケットに遅延を発生させる場合において、遅延時間を高精細にシミュレーションするためにスピンロックを使用せず、OS によるタイマ割り込みによって遅延を発生させるようにします。これにより CPU 使用率が低下しますが、発生させることができる遅延の精度は低くなります。"},
        {QStringLiteral("BroadcastStormDetectionThreshold"), "大量のブロードキャストパケットが仮想 HUB に同一のセッションから投入された場合に、ブロードキャストストームであると判定するための閾値を指定します。1 秒間あたりのパケット個数を指定します。指定しない場合 (0 の場合) は 32 が使用されます。"},
        {QStringLiteral("ClientMinimumRequiredBuild"), "この項目が 1 以上に設定されている場合は、設定されている数値よりもビルド番号が小さい VPN Client が接続してきた場合に VPN 接続を拒否します。"},
        {QStringLiteral("RequiredClientId"), "この項目が 1 (有効) の場合は、この整数と同一の「クライアント ID」が埋め込まれている VPN Client ソフトウェアだけがこの仮想 HUB に接続でき、それ以外の VPN Client は接続できなくなります。"},
        {QStringLiteral("AdjustTcpMssValue"), "この項目が 1 (有効) の場合は、この仮想 HUB を経由して通信が行われるすべての TCP/IP パケットの MSS (Max Segment Size) をこの項目で指定したバイト数以下になるように自動調整します。"},
        {QStringLiteral("DisableAdjustTcpMss"), "この項目が 1 (有効) の場合は、この仮想 HUB におけるいかなる MSS (Max Segment Size) も無効にします。AdjustTcpMssValue オプションが指定されている場合や、IPsec / L2TP / EtherIP / L2TPv3 サーバー機能によって受け付けた VPN 通信が行われる場合においても、MSS の調整は行われなくなります。"},
        {QStringLiteral("NoDhcpPacketLogOutsideHub"), "この項目が 1 (有効) の場合は、仮想 HUB 内に到達した DHCP による IP アドレス割当パケットのうち、この仮想 HUB に接続されているセッションと無関係のものについてログを保存しないようにします。"},
        {QStringLiteral("DisableHttpParsing"), "この項目が 1 (有効) の場合は、仮想 HUB は内部的にすべての HTTP パケットの HTTP ヘッダを解釈しないようになります。これにより VPN Server の CPU およびメモリの使用量を削減することができますが、HTTP アクセスログが保存されなくなります。"},
        {QStringLiteral("DisableUdpAcceleration"), "この項目が 1 (有効) の場合は、この仮想 HUB に対して接続されるすべての VPN セッションにおいて UDP 高速化機能の使用を禁止します。"},
        {QStringLiteral("DisableUdpFilterForLocalBridgeNic"), "この項目が 1 (有効) の場合は、仮想 HUB 内で作成されるローカルブリッジを構成する物理的な LAN カードが VPN を経由して遠隔地の DHCP サーバーから IP アドレスの割当を受けることで動作が不安定になる問題を解決するための DHCP パケットフィルタリング動作を無効にします。"},
        {QStringLiteral("ApplyIPv4AccessListOnArpPacket"), "この項目が 1 (有効) の場合は、仮想 HUB 内で定義されている IPv4 アクセスリストのルールを ARP パケットにも適用します。不要な ARP 要求パケットを遮断したい場合に便利です。"},
        {QStringLiteral("RemoveDefGwOnDhcpForLocalhost"), "この項目が 1 (有効) の場合は、DHCP サーバーが仮想 HUB に接続された VPN クライアントに IP アドレスを割当てる際に、当該 VPN クライアントが VPN Server が動作しているコンピュータと同一である場合は DHCP 応答パケットからデフォルトゲートウェイの指定を削除します。これにより、意図しない無限ループを防止することができます。"},
        {QStringLiteral("SecureNAT_MaxTcpSessionsPerIp"), "この項目が 0 以外に設定されている場合は、SecureNAT 機能を利用する VPN クライアント 1 台あたりの TCP コネクション数 (SYN_SENT 状態以外の TCP コネクション) のこの項目で指定した数に制限されます。"},
        {QStringLiteral("SecureNAT_MaxTcpSynSentPerIp"), "この項目が 0 以外に設定されている場合は、SecureNAT 機能を利用する VPN クライアント 1 台あたりの TCP コネクション数 (SYN_SENT 状態の TCP コネクション) のこの項目で指定した数に制限されます。"},
        {QStringLiteral("SecureNAT_MaxUdpSessionsPerIp"), "この項目が 0 以外に設定されている場合は、SecureNAT 機能を利用する VPN クライアント 1 台あたりの UDP セッション数のこの項目で指定した数に制限されます。"},
        {QStringLiteral("SecureNAT_MaxDnsSessionsPerIp"), "この項目が 0 以外に設定されている場合は、SecureNAT 機能を利用する VPN クライアント 1 台あたりの DNS セッション数のこの項目で指定した数に制限されます。"},
        {QStringLiteral("SecureNAT_MaxIcmpSessionsPerIp"), "この項目が 0 以外に設定されている場合は、SecureNAT 機能を利用する VPN クライアント 1 台あたりの ICMP セッション数のこの項目で指定した数に制限されます。"},
        {QStringLiteral("AccessListIncludeFileCacheLifetime"), "仮想 HUB のアクセスリストのエントリにユーザー名が \"include:\" または \"exclude:\" 形式で指定されており、外部ファイルを参照している場合、当該外部ファイルを読み込んでからメモリにキャッシュする時間を秒単位で指定します。"},
        {QStringLiteral("DisableKernelModeSecureNAT"), "この項目が 1 (有効) の場合は、SecureNAT 機能におけるカーネルモード NAT を無効にします。カーネルモード NAT は、SecureNAT の仮想 NAT 機能の動作速度を高速化するための機能であり、VPN Server プロセスがシステム権限で動作している場合に使用できます。カーネルモード NAT が原因で何らかの通信障害が発生した場合はこのオプションを使用してカーネルモード NAT を無効にしてください。"},
        {QStringLiteral("DisableUserModeSecureNAT"), "この項目が 1 (有効) の場合は、SecureNAT 機能におけるユーザーモード NAT を無効にします。ユーザーモード NAT は、SecureNAT の仮想 NAT 機能を一般ユーザー権限で動作させるための機能であり、VPN Server プロセスが一般ユーザー権限で動作している場合でも使用できます。"},
        {QStringLiteral("DisableCheckMacOnLocalBridge"), "この項目が 1 (有効) の場合は、ローカルブリッジ機能において MAC アドレスの重複チェックを無効にします。一部の LAN カードでは、ローカルブリッジ機能によって送出されたパケットが LAN カード内部で反射し仮想 HUB に戻ってくる場合があります。この場合、仮想 HUB は MAC アドレスの重複を自動的に検出し、反射してきたパケットを破棄します。このフラグを有効にすると、この検出チェックが無効になります。"},
        {QStringLiteral("DisableCorrectIpOffloadChecksum"), "この項目が 1 (有効) の場合は、ローカルブリッジ機能において IP チェックサムの検査および補正処理が無効になります。IP, TCP, UDP ヘッダのチェックサムのオフロード機能が搭載されている LAN カードから送信された IP パケットが同一ホスト上で動作する VPN Server のローカルブリッジに入力された場合、当該 IP パケットのチェックサムは不正確な値が代入されている場合があります。ローカルブリッジはデフォルトでその不正確な値を検出し、正しいチェックサムの計算結果を代入します。このフラグを有効にすると、これらの補正処理が無効になります。"},
        {QStringLiteral("BroadcastLimiterStrictMode"), "この項目が 1 (有効) の場合は、仮想 HUB 上のセッションにおけるブロードキャストストームの検出アルゴリズムにおいて、送信元 IP アドレスまたは宛先 IP アドレスのいずれか 1 個が一致していれば既存の検出用記録とヒットしたとみなします。"},
        {QStringLiteral("MaxLoggedPacketsPerMinute"), "1 分間あたりにパケットログに保存することができる最大のパケット数を指定します。"},
        {QStringLiteral("DoNotSaveHeavySecurityLogs"), "保存に負荷がかかるセキュリティログを保存しない設定をします。"},
        {QStringLiteral("DropBroadcastsInPrivacyFilterMode"), "送信元および宛先の両方のセッションがプライバシーフィルタモードの場合、ブロードキャストパケットを破棄します。"},
        {QStringLiteral("DropArpInPrivacyFilterMode"), "送信元および宛先の両方のセッションがプライバシーフィルタモードの場合、ARP パケットを破棄します。"},
        {QStringLiteral("AllowSameUserInPrivacyFilterMode"), "プライバシーフィルターモードであっても、送信元セッションと宛先セッションの両方が同じユーザーである場合は、パケットを許可します。"},
        {QStringLiteral("SuppressClientUpdateNotification"), "VPN Client のアップデート通知画面の表示を抑制します。"},
        {QStringLiteral("FloodingSendQueueBufferQuota"), "パケットの仮想 HUB 内におけるフラッディング動作時において消費することを許容する送信キューのバッファサイズの制限値 (バイト数) を指定します。クオータは、すべての接続中の VPN セッションの送信キューの合計長さに対してグローバルに適用されます。0 を指定すると無制限になります。このオプションは、フラッディングパケットが多発するネットワークにおいてメモリ消費量が増大する問題を解決するために利用できます。"},
        {QStringLiteral("AssignVLanIdByRadiusAttribute"), "VLAN ID の動的割り当て機能を有効にします。VPN 接続するユーザーオブジェクトのセキュリティポリシーに VLAN ID が指定されていない場合は、各 VPN セッションはユーザー認証を行った RADIUS サーバーから返却される RADIUS 属性の値に基づき VLAN が割当てられます。RADIUS 属性のうち、 \"Tunnel-Pvt-Group-ID\" (ID = 81) の値が使用されます。データ型は文字列である必要があります。"},
        {QStringLiteral("DenyAllRadiusLoginWithNoVlanAssign"), "この項目が 1 (有効) の場合は、RADIUS サーバーが \"Tunnel-Pvt-Group-ID\" (ID = 81) の値を返却しなかった場合は VPN 接続が拒否されます。(AssignVLanIdByRadiusAttribute の値が 1 の場合に限ります。)"},
        {QStringLiteral("SecureNAT_RandomizeAssignIp"), "この項目が 1 (有効) の場合は、SecureNAT 機能における仮想 DHCP サーバーは、DHCP クライアントに対して割当てる IP アドレスを指定された IP アドレスプール内の未使用アドレスからランダムに選択するようになります。なお、既定の動作は、未使用アドレスのうち最初のアドレスを割当てるようになっています。"},
        {QStringLiteral("DetectDormantSessionInterval"), "この項目が 0 以外の場合は、指定された秒数無通信であった VPN セッションをドーマント状態 (休止状態) として識別します。ドーマント状態の VPN セッションに対しては、仮想 HUB 内でフラッディングされるべきパケットがフラッディングされなくなります。"},
        {QStringLiteral("NoPhysicalIPOnPacketLog"), "この項目が 1 (有効) の場合は、パケットログに送信元および宛先 VPN セッションの物理的な接続元 VPN クライアントの IP アドレスが記録されないようになります。"},
        {QStringLiteral("UseHubNameAsDhcpUserClassOption"), "この項目が 1 (有効) の場合は、仮想 HUB は DHCP サーバーに対して IP アドレスの取得を要求する際に仮想 HUB 名を DHCP パケットの \"User-Class\" オプションに埋め込むようになります。この機能は、複数の仮想 HUB がある場合に、DHCP サーバーがそれぞれの仮想 HUB 用に IP プールを確保する場合に便利です。(L2TP/IPsec および OpenVPN セッションのみ対応。)"},
        {QStringLiteral("UseHubNameAsRadiusNasId"), "この項目が 1 (有効) の場合は、NAS-Identifier RADIUS 属性に仮想 HUB 名が埋め込まれます。この機能は、RADIUS サーバにおいて仮想 HUB ごとにアクセスの許可 / 拒否を設定したい場合に便利です。"},
        {QStringLiteral("AllowEapMatchUserByCert"), "If you enable (set to 1) this option, the Virtual Hub will attempt to match the EAP Identity not only with usernames, but also with user certificates during the PPP EAP authentication flow."},
    };
    const auto it = table.constFind(name);
    return it == table.constEnd() ? QString() : QCoreApplication::translate("HubOptionTexts", it.value());
}

} // namespace HubOptionTexts
